### ISSUE TITLE
Use MLFlow in AIF360 for logging metrics & tracking experimentation

### ISSUE THREAD

**Issue by anupamamurthi** [Trusted-AI/AIF360#344]
MLFLow is an open source tool https://github.com/mlflow/mlflow/ that can help with various ML related tasks.

The goal behind including MLFLow to AIf360 is that, as and when someone runs a HPO or a large set of experiments, mlflow will make it very easy to track the experimentation work.

Refer to some examples here: https://www.mlflow.org/docs/latest/tutorials-and-examples/tutorial.html

- [ ] Learn about MLFlow (and how it can be used for rapid experimentation and how it can be used for tracking ML metrics)
- [ ] Make a plan on how it fits into AIF360
- [ ] Create/Redo one example notebook and show how MLFLow can be leveraged by this toolkit
- [ ] Make updates to requirements.txt and README explaining how mlflow server should be started (a simple script maybe required to do this and some set up process)
